### ISSUE TITLE
gcc linux compilation fail

### ISSUE THREAD

**Issue by Kuranes** [cedricpinson/envtools#1]
non standard math function doesn't work on gcc (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1 
sincosf,etc it needs "macro" or perhaps disabling the strict  std99 cf http://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

"Outside strict ISO C mode (-ansi, -std=c90, -std=c99 or -std=c11), the functions [..] sincosf, sincosl, sincos, [..] may be handled as built-in functions. All these functions have corresponding versions prefixed with __builtin_, which may be used even in strict C90 mode."

**Comment by Kuranes** [comment]
tried with 

``` Makefile
CFLAGS= -std=c99 -pedantic -Wall -O3 -fstrict-aliasing -fopenmp -fpic
LDFLAGS= -O3 -fstrict-aliasing -fopenmp -shared
...
...
%   : %.o
    $(LD) $(LDFLAGS) $(LIBS) -o $@ $^
...
...
```

and got all of it compiling but envtospecular.

Getting compilation error on envtospecular.cpp:
envtospecular.cpp:43:55 error 'Vec2D' has not been declared
etc.

**Comment by cedricpinson** [comment]
It's now using cmake does it continue to fail ?

**Comment by cedricpinson** [comment]
fixed
